### ISSUE TITLE
Ambiguity of Web link in Wing creation

### ISSUE THREAD

**Issue by abhishekmsingh** [GeekHaven/GeekHaven-2020#15]
In the `onstart.php` file, the wings table contains five columns `wing_id, wing, info, logo, image` whereas during creation, the `savewing.php` runs the query `INSERT INTO wings VALUES('$wing_id','$wing','$info','$logo','$image','$link')`  which contains 6 fields which obviously causes an error. 
I suggest to remove the `link` param for good and use the url of the form `http://geekhaven.com/wings.php?id=wing_id`. Please fix this asap!

**Comment by pradhuman1** [comment]
Issue Solved
