### ISSUE TITLE
Removal of unwanted assets

### ISSUE THREAD

**Issue by abhishekmsingh** [GeekHaven/GeekHaven-2020#16]
Since we have made the sites dynamic, there is no need for static assets unless uploaded. Remove all the static assets and make a repo(any of the dev can do it) and I will then transfer it to Geekhaven. Feel free to discuss alternatives.

**Comment by abhishekmsingh** [comment]
Also the new repo should be the previously completed static site(hence implicitly containing all the static assets) so that we can use it as a design reference. I think you all understand that. Please ask if there is any doubt.

**Comment by garvitchittora** [comment]
Done 👍 
[Code](https://github.com/garvitchittora/Geekhaven-20-StaticFiles)
[live link](https://garvitchittora.github.io/Geekhaven-20-StaticFiles/)

**Comment by garvitchittora** [comment]
@infern018 review it.
