### ISSUE TITLE
Shifting of the wing image

### ISSUE THREAD

**Issue by abhishekmsingh** [GeekHaven/GeekHaven-2020#17]
So I created a new wing and uploaded the respective assets. But when I went to the wing page the wing image was offset. Have a look,
![image](https://user-images.githubusercontent.com/47845897/88478101-38360e00-cf63-11ea-88f6-57db40628018.png)
First of all why is this happening. Secondly, what is the probable fix?

**Comment by abhishekmsingh** [comment]
Also the `.` after hello was not dynamically added and is hardcoded in the code, is it a coding mistake?

**Comment by garvitchittora** [comment]
I think the image is shifted because of the description size.

**Comment by abhishekmsingh** [comment]
Any fix for that?

**Comment by infern018** [comment]
![Screenshot (98)](https://user-images.githubusercontent.com/52378712/88483478-d6d36680-cf85-11ea-80cc-a3097b47b760.png)

Fixed the shifting of image and extra '.' after sub heading

**Comment by abhishekmsingh** [comment]
@garvitchittora @pradhuman1 please review the changes

**Comment by abhishekmsingh** [comment]
And close the issue if solved
