### ISSUE TITLE
Image in announcement card

### ISSUE THREAD

**Issue by pradhuman1** [GeekHaven/GeekHaven-2020#20]
Add an 'img' tag in announcement card which is on wing page.

**Comment by AlacritousCreature** [comment]
I want to work on this. May I?

**Comment by garvitchittora** [comment]
@AlacritousCreature go ahead 🎉

**Comment by Parasagrawal** [comment]
i want to work on this

**Comment by pradhuman1** [comment]
@AlacritousCreature any progress?

**Comment by AlacritousCreature** [comment]
Hey @pradhuman1! I had problems in setuping it locally yesterday...I tried to do in sandbox but the things stored in database aren't visible in it.....I will do it today.....please let me do it in few hours.

**Comment by AlacritousCreature** [comment]
Hey! could guide a bit, like where to add a image in announcements on wings page? I mean where and of what size

![Screenshot (241)](https://user-images.githubusercontent.com/58398802/95826879-9bf4f980-0d50-11eb-8ff1-37cc1e635f2f.png)
 

I am new to php and don't know the structure of it well.......just wanted to make sure that I have to add image tag in 'wing.php' file :sweat_smile:......under this section


![Screenshot (242)](https://user-images.githubusercontent.com/58398802/95827475-6b618f80-0d51-11eb-886c-311c7dcf018d.png)

**Comment by pradhuman1** [comment]
yes
add an img tag which will display image as a background of date(i.e JUNE 21)
try to make image blur so that it would look like a portrait
