### ISSUE TITLE
One blog displayed as three

### ISSUE THREAD

**Issue by abhishekmsingh** [GeekHaven/GeekHaven-2020#25]
Visit
http://geekhaven.epizy.com/GeekHaven-2020/complete_list/blogs/blog.php?id=1598678672000,
There is only one blog, but three are being displayed.
Is this intentional @garvitchittora @pradhuman1 @infern018 

P.S:- Thanks to @Lazy-Leopard for pointing this out

**Comment by abhishekmsingh** [comment]
Is it because of the infinite scroll thing, it causes the repetition because the first and the last blog are the same, here? 
It's acceptable behavior, right?

**Comment by divyanshrai655** [comment]
> Is it because of the infinite scroll thing, it causes the repetition because the first and the last blog are the same, here? 
> It's acceptable behavior, right?

Got it , and feel that the issue requires not much attention,and must be therefore closed.

**Comment by abhishekmsingh** [comment]
Okay thanks @Lazy-Leopard for finding this. Closing!
