### ISSUE TITLE
Official website not reachable

### ISSUE THREAD

**Issue by KShivendu** [GeekHaven/GeekHaven-2020#29]
Hii. You might be aware that https://geekhaven.iiita.ac.in/ isn't working. I'm reporting it so this issue gets noticed (if it wasn't). I hope it gets fixed soon :)

Cheers!

**Comment by abhishekmsingh** [comment]
Hey @KShivendu thanks for reaching out to us. Unfortunately that is a problem with the IIITA deployment and not in the hand of developers. I don't know what kind of servers they are using tbh, this is happening from time to time. I will let them know about this problem.

**Comment by abhishekmsingh** [comment]
Don't worry you didn't report a non issue. The status keeps fluctuating from time to time. Sometime it's down and sometimes it's up

**Comment by KShivendu** [comment]
Ahh, I see. I thought I had some misunderstanding. 😂
